### ISSUE TITLE
Add helper method title

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/rubywork_ru#13]
We want to set title for web page, we can do it in each pages, but better create helper method for this (https://apidock.com/rails/ActionView/Helpers/CaptureHelper/content_for)
1) Create in application_helper(couse we will call the method in different pages) **title** with argument **page_title**
2) Call content_for with argument :title and block { page_title }
3) In main layout.html in header set
```
 <title><%= content_for?(:title) ? yield(:title) : "RubyWork" %></title>
```

**Comment by odanetpro** [comment]
I want to take the issue

**Comment by XaoGao** [comment]
@odanetpro ok
