### ISSUE TITLE
Add roles to user

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/rubywork_ru#16]
After #7 system will be use different user, add a new colum **role** in **user** model add AR enum to model **user** with values :applicant, :company, :moderator, :admin

**Comment by o-200** [comment]
I want to take the issue

**Comment by o-200** [comment]
I want to take the issue

**Comment by XaoGao** [comment]
@o-200 ok

**Comment by o-200** [comment]
@XaoGao solution is ready for checking ^
