### ISSUE TITLE
Add simplecov gem

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/rubywork_ru#29]
After #4  #5 For checking test coverage we will use gem **simplecov**, add gems and configure in specl_helper, run test and ensure html in gitigore file https://rubygems.org/gems/simplecov

**Comment by o-200** [comment]
i want to take the issue

**Comment by XaoGao** [comment]
@o-200 ok

**Comment by o-200** [comment]
@XaoGao Complete, check PR ^
