### ISSUE TITLE
Add rspec

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/rubywork_ru#4]
All ruby projects need to be tested, for this we will use rspec gems https://github.com/rspec, 
1) Add gem rspec (last version) in gemfile in test group https://rubygems.org/gems/rspec
2) Add gem rspec-rails (last version in gemfile in test group) https://rubygems.org/gems/rspec-rails
3) Run in terminal
```
bundle install
```
4) Install rspec in project 
```
rails generate rspec:install
```
5) Remove all comments in spec/spec_helper.rb file

**Comment by antoni668** [comment]
Комментарии между begin и end удалять нужно? Или они какую-то функцию выполняют?

**Comment by XaoGao** [comment]
@antoni668  они используются для много строчных комментариях, тоже нужно удалить , ты хочешь взять эту задачу?

**Comment by antoni668** [comment]
> @antoni668 они используются для много строчных комментариях, тоже нужно удалить , ты хочешь взять эту задачу?

Да, хочу взять. Нужно сначала сказать, что хочу взять, потом начинать делать? Я хотел все задачи по очереди делать какие есть.

**Comment by XaoGao** [comment]
@antoni668 да, перед тем как делать задачу надо спросить, почитай readme, так же всегда ставь тег кому пишешь, если будет больше людей возникает путаница, многострочный комментарии тоже надо удалить
