### ISSUE TITLE
Add rubocop-rspec

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/rubywork_ru#5]
After #4 add gem rubocop-rspec for support style in test
1) Add gem "rubocop-rspec" last version in develop group https://rubygems.org/gems/rubocop-rspec
2) Run
```
bundle install
```
3) Add to the file [.rubocop.yml](https://github.com/XaoGao/rubywork_ru/pull/3/files/877d91ce3b5158ec328a95c171ab7df148947aad#diff-4f894049af3375c2bd4e608f546f8d4a0eed95464efcdea850993200db9fef5c)
in require section
```
rubocop-rspec
```

**Comment by antoni668** [comment]
@XaoGao хочу эту задачу взять, можно?

**Comment by XaoGao** [comment]
@antoni668 ок

**Comment by antoni668** [comment]
@XaoGao Нормальный пулл реквест? Не принимаешь и комментария твоего не вижу.

**Comment by antoni668** [comment]
@XaoGao А, ты в другом месте коммент оставил, я не увидел сразу.
