### ISSUE TITLE
Add gem dotenv

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/rubywork_ru#50]
We will keep env variable(like db password) in .env file
1) add gem https://rubygems.org/gems/dotenv-rails
2) create file .env.example with
POSTGRES_USER=postges
POSTGRES_PASSWORD=changeme
DATABASE_HOST=127.0.0.1
DATABASE_PORT=54320
REDIS_URL="redis://localhost:63790/1"
3) add to gitignore file .env file (NOT .env.example)

**Comment by proskurekov** [comment]
I want to take the issue
