### ISSUE TITLE
Add name to the user

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/rubywork_ru#52]
Add new field "name" (each company has name and each user has first_name, last_name etc) add validations
name - string - null able

**Comment by XaoGao** [comment]
Add this field in device view

**Comment by odanetpro** [comment]
I want to take the issue

**Comment by XaoGao** [comment]
@odanetpro ok

**Comment by odanetpro** [comment]
@XaoGao Why add this validation? These conditions (name - string - null able) do not require checking.
Maybe you want the name to have only letters? Then what about the company name 37signals?
