### ISSUE TITLE
Add welcome controller with first page

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/rubywork_ru#6]
After #4  #5 We needed first controller like root path
1) Run command
```
rails g controller Pages
```
This creates a controller and test file
2) Add empty method "welcome" to the controller
3) Add to the file https://github.com/XaoGao/rubywork_ru/blob/main/config/routes.rb 
```ruby
root "pages#welcome"
```
4) Add to view app/views/pages/welcome.html.erb
```
<h1> This a welcome page<h1>
```
5) Check project is running, open browser in localhost:3000 and show the message

**Comment by antoni668** [comment]
@XaoGao возьму задачу?

**Comment by XaoGao** [comment]
@antoni668 ok
