### ISSUE TITLE
Add devise

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/rubywork_ru#7]
After #6. For auth we will use devise gem https://github.com/heartcombo/devise
1) Add devise gem in gemfile with last version https://rubygems.org/gems/devise
2) Run
```
bundle install
```
3) Run
```
rails generate devise:install
```
4) Run
```
rails generate devise User
```
5) Add to config/root.rb
```
devise_for :users
```
6) Run
```
rails db:migrate
```
7) Launch project, open root path (localhost:3000) check db have the table Users and page opened without errors

**Comment by ekatebenkova** [comment]
I want to take the issue

**Comment by XaoGao** [comment]
@ekatebenkova ok

**Comment by realvint** [comment]
Add gem 'devise-i18n' for translations
