### ISSUE TITLE
Add new enum to resume model

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/rubywork_ru#82]
Add enum status to model resume, options: open, hide, irrelevant default value **open**

**Comment by FaxriddinMaxmadiyorov** [comment]
hello, I want to take this issue

**Comment by FaxriddinMaxmadiyorov** [comment]
@XaoGao hello, open, hide, irrelevant default value open: I think instead of hide it must be hidden; because hide is a verb, hidden is adjective
