### ISSUE TITLE
Add buttons to vacancies

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/rubywork_ru#86]
Add 2 buttons in navbar
First: "Vacancies" redirect to all vacancies
Second: "My vacancies" redirect to new method in vacancies controller where get vacancies belong to user
Write spec

**Comment by FaxriddinMaxmadiyorov** [comment]
@XaoGao hello, I want to take this issue

**Comment by XaoGao** [comment]
@FaxriddinMaxmadiyorov ok
