### ISSUE TITLE
Add docker-compose file

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/rubywork_ru#9]
We want to collect all the dependencies in project, participants should not set separate dependencies for the project.
1) Create in main dir file
```
.docker-compose.yml
``` 
2) File use 
```
version '3.5'
```
3) Add services:

- container_name: postgres_container
    image: postgres:14

- container_name: pgadmin_container
    image: dpage/pgadmin4

- cache:
    image: redis:6.2-alpine

**Comment by antoni668** [comment]
@XaoGao Возьму эту задачу?

**Comment by o-200** [comment]
i want to take this issue

**Comment by o-200** [comment]
@XaoGao

**Comment by XaoGao** [comment]
@o-200 ok

**Comment by o-200** [comment]
@XaoGao its ready -> #76
